import { create } from "zustand";

/**
 * Interface representing a column inside a generated table output from the assistant.
 */
interface TableColumn {
  key: string;
  label: string;
}

/**
 * Interface representing a single row of data dynamically generated by the assistant.
 */
interface TableRow {
  [key: string]: string | number;
}

/**
 * Interface representing a core KPI or metric returned alongside textual analysis.
 */
interface Metric {
  label: string;
  value: string | number;
  backgroundColor?: string;
  textColor?: string;
}

/**
 * Comprehensive dataset representation containing rows and column definitions.
 */
interface TableData {
  columns: TableColumn[];
  rows: TableRow[];
}

/**
 * Central interface defining the structure of a chat message in the CLI tool.
 * Crucially, it manages state across different contexts using the 'mode' field.
 */
interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
  mode: "text" | "chart" | "dashboard";
  /** Optional structured payload containing metrics, table records, or chart configuratons. */
  data?: {
    tableData?: TableData;
    metrics?: Metric[];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    chartOptions?: any;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    dashboardData?: any;
  };
}

/**
 * Zustand global state manager orchestrating chat histories and assistant responses.
 */
interface CombinedChatStore {
  messages: ChatMessage[];
  isLoading: boolean;
  
  addMessage: (message: Omit<ChatMessage, "id" | "timestamp">) => void;
  setLoading: (loading: boolean) => void;
  clearMessages: () => void;
}

export const useCombinedChatStore = create<CombinedChatStore>((set, get) => ({
  messages: [],
  isLoading: false,

  /**
   * Appends a newly sent user message or generated assistant response to the active CLI session.
   * Auto-generates unique deterministic IDs and timestamps.
   * 
   * @param {Omit<ChatMessage, "id" | "timestamp">} message - The message payload to inject.
   */
  addMessage: (message) => {
    const newMessage: ChatMessage = {
      ...message,
      id: Date.now().toString() + Math.random(),
      timestamp: new Date(),
    };

    set((state) => ({
      messages: [...state.messages, newMessage],
    }));
  },

  /**
   * Toggles the loading status overlay when performing intensive operations in the CLI.
   * 
   * @param {boolean} loading - True if processing an action, false otherwise.
   */
  setLoading: (loading) => set({ isLoading: loading }),

  /**
   * Clears out all active chat records to provide a fresh, unpolluted workspace.
   */
  clearMessages: () => set({ messages: [] }),
}));
